# Move templates to a dedicated constant mapping file or module top
PROMPT_TEMPLATES = {
    "sql": (
        "### Context\n"
        "You are a professional analytics assistant. Synthesize the provided data "
        "into a clean, structured response according to the requested format. "
        "Do not use preambles like 'Based on the data'.\n\n"
        "### Inputs\n"
        "- Question: {query}\n"
        "- SQL Result: {sql_data}\n\n"
        "### Target Layout\n"
        "**Data Summary**\n"
        "[List the numerical values, counts, names, or metrics found in the SQL result using bullet points.]\n\n"
        "**Key Insight**\n"
        "[A single concise sentence translating this metric or data trend into business value.]\n\n"
        "Final Structured Answer:"
    ),
    "rag": (
        "### Context\n"
        "You are a professional analytics assistant. Synthesize the provided data "
        "into a clean, structured response according to the requested format. "
        "Do not use preambles like 'Based on the data'.\n\n"
        "### Inputs\n"
        "- Question: {query}\n"
        "- RAG Result: {rag_data}\n\n"
        "### Target Layout\n"
        "CRITICAL STEP: Evaluate if the user's question is a simple greeting or conversation opener (e.g., 'hi', 'how are you', etc).\n"
        "1. IF IT IS A GREETING: Provide a warm, friendly, professional response welcoming the user. "
        "Briefly state that you can help them with sales analytics, product data, or operations policies. "
        "Do NOT use bullet points or headers like '**Policy Guidelines**'.\n"
        "2. IF IT IS A POLICY QUESTION: Use this layout structure instead:\n"
        "**Policy Guidelines**\n"
        "[Summarize the relevant company rules or compliance context in bullet points.]\n\n"
        "**Key Insight**\n"
        "[A single concise sentence explaining the immediate takeaway from this policy.]\n\n"
        "Final Structured Answer:"
    ),
    "hybrid": (
        "### Context\n"
        "You are a professional analytics assistant. Synthesize the provided data "
        "into a clean, structured response according to the requested format. "
        "Do not use preambles like 'Based on the data'.\n\n"
        "### Inputs\n"
        "- Question: {query}\n"
        "- SQL Result: {sql_data}\n"
        "- RAG Result: {rag_data}\n"
        "- Hybrid Context: {hybrid_data}\n\n"
        "### Target Layout\n"
        "**Data Summary**\n"
        "[List specific metrics or items from the database in bullet points.]\n\n"
        "**Policy Guidelines**\n"
        "[Summarize the company compliance rules tied to these specific data items.]\n\n"
        "**Key Insight**\n"
        "[A single sentence explicitly linking the database data directly to the policy rules.]\n\n"
        "Final Structured Answer:"
    )
}